### ISSUE TITLE
Some (custom) Elvis fields are not editable when using an API user

### ISSUE THREAD

**Issue by kmplngj** [WoodWing/elvis-image-recognition#14]
Hello,

I setup the service with default settings. I have two problem regarding the custom-assetinfo.xml.

1. Some of the added custom fields like `cf_partialMatchingImages` are setup with `editable="false"`. So my API user could not write the data.

2.`Error: Elvis request failed: Access is denied, no permission to edit fields: [textContent]` This default field is also defined as `editable="false"`.

I use an API user that has permission to the images and to all available meta data.

How could I fix this? What could be wrong in my setup?

Thanks

**Comment by jaapvanblaaderen** [comment]
The custom fields should indeed be editable, so this looks like an incorrect sample config. The textContent field is not suitable to store OCR'ed text as it's not editable by API users, so that needs change as well.

**Comment by jaapvanblaaderen** [comment]
Issue is fixed, please retry with latest code + config as now available in master. You can re-open the ticket if you still have issues.
